background = #181614
foreground = #E6DFD3
cursor-color = #C9A66B
selection-background = #2F2924
selection-foreground = #E6DFD3

palette = 0=#2F2924
palette = 1=#C47064
palette = 2=#7D9A8C
palette = 3=#C9A66B
palette = 4=#708C8F
palette = 5=#A88B6E
palette = 6=#7FA195
palette = 7=#E7E0D4
palette = 8=#8A8278
palette = 9=#D67B6F
palette = 10=#89A792
palette = 11=#D4A05A
palette = 12=#7F989A
palette = 13=#B99777
palette = 14=#83AC9E
palette = 15=#EAE4D9
