background = #322821
foreground = #E8DED0
cursor-color = #D5AB68
selection-background = #44382F
selection-foreground = #E8DED0

palette = 0=#44382F
palette = 1=#D17469
palette = 2=#81A191
palette = 3=#D5AB68
palette = 4=#799194
palette = 5=#B59274
palette = 6=#82A89B
palette = 7=#E8DED0
palette = 8=#91867A
palette = 9=#E07F73
palette = 10=#8DAE98
palette = 11=#DDA55C
palette = 12=#839EA1
palette = 13=#C49B7C
palette = 14=#88B2A4
palette = 15=#E9E2D6
